//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyCopyright("Copyright © 2015. All rights reserved.")]
[assembly: System.Reflection.AssemblyConfiguration("Debug")]
[assembly: System.Reflection.AssemblyVersion("0.0.1")]
[assembly: System.Reflection.AssemblyFileVersion("0.0.1")]
[assembly: System.Reflection.AssemblyInformationalVersion("0.0.1")]



internal sealed partial class ThisAssembly {
    
    internal const string AssemblyCopyright = "Copyright © 2015. All rights reserved.";
    
    internal const string AssemblyConfiguration = "Debug";
    
    internal const string AssemblyVersion = "0.0.1";
    
    internal const string AssemblyFileVersion = "0.0.1";
    
    internal const string AssemblyInformationalVersion = "0.0.1";
    
    private ThisAssembly() {
    }
}
