//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyProduct("Mumble.NET")]
[assembly: System.Reflection.AssemblyCompany("https://github.com/perrym5/Mumble.NET")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © 2015. All rights reserved.")]
[assembly: System.Reflection.AssemblyConfiguration("Debug")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(false)]



internal sealed partial class ThisAssembly {
    
    internal const string AssemblyProduct = "Mumble.NET";
    
    internal const string AssemblyCompany = "https://github.com/perrym5/Mumble.NET";
    
    internal const string AssemblyCopyright = "Copyright © 2015. All rights reserved.";
    
    internal const string AssemblyConfiguration = "Debug";
    
    private ThisAssembly() {
    }
}
